### ISSUE TITLE
System.IO.IOException: unknown packet type encountered: 20

### ISSUE THREAD

**Issue by MacMuffin** [Cinchoo/ChoPGP#41]
Hey,

first of all i want to thank you for this great package! I like how easy it is for using, thanks for that!

I have one question. We have suddenly, without changing or updating the application or something, encountered the following error:

```
System.IO.IOException: unknown packet type encountered: 20
   at Org.BouncyCastle.Bcpg.BcpgInputStream.ReadPacket()
   at Org.BouncyCastle.Bcpg.OpenPgp.PgpEncryptedDataList..ctor(BcpgInputStream bcpgInput)
   at Org.BouncyCastle.Bcpg.OpenPgp.PgpObjectFactory.NextPgpObject()
   at Cinchoo.PGP.ChoPGPEncryptDecrypt.Decrypt(Stream inputStream, Stream outputStream, Stream privateKeyStream, String passPhrase)
   at Cinchoo.PGP.ChoPGPEncryptDecrypt.Decrypt(Stream inputStream, Stream outputStream, String privateKeyFilePath, String passPhrase)
```

It happens one week ago without any changes, so i asking myself, what could cause the issue? We tried some things to check, key is still valid, because we can decrypt the encrypted file with the gpg command in Windows PowerShell.

We tried also to change the key, but same thing happens, also if you provide an invalid key.

Any Idea what could happen here?

Thats the call were the Issue happens: 
`using (var pgp = new ChoPGPEncryptDecrypt())
                  {
                      pgp.Decrypt(memInput, memOutput, _appSettings.ImportSettings.DecryptPrivateKeyPath, "");
                  }`

on pgp.Decrypt

Thank you in advance!

BR

**Comment by BrewmeisterP** [comment]
You must have encrypted the file using Kleopara.  It creates a "packet 20" that is not standard and causes this error.  So....don't encrypt via Kleopatra - that's the only solution.  Or...I guess, decrypt using Kleo, too.
